# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0002_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackuser',
            name='slack_channel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
